/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calculadora.view;

import groovy.lang.Binding;
import groovy.lang.GroovyShell;
import java.awt.Color;

/**
 *
 * @author marcelo
 */
public class Main extends javax.swing.JFrame {
    int LayoutX,LayoutY;
    Binding binding = new Binding();
    GroovyShell gshell = new GroovyShell();
    String formula = "";
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        pnl_tiltleBar = new javax.swing.JPanel();
        btn_sair = new javax.swing.JButton();
        btn_minimizar = new javax.swing.JButton();
        pnl_result = new javax.swing.JPanel();
        tfd_formula = new javax.swing.JTextField();
        tfd_result = new javax.swing.JTextField();
        pnl_btns = new javax.swing.JPanel();
        btn_limpar = new javax.swing.JButton();
        btn_divisao = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_fechaParentese = new javax.swing.JButton();
        btn_abreParentese = new javax.swing.JButton();
        btn_subtrair = new javax.swing.JButton();
        btn_soma = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_resultado = new javax.swing.JButton();
        btn_ponto = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_00 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setUndecorated(true);

        pnl_tiltleBar.setBackground(new java.awt.Color(52, 60, 79));
        pnl_tiltleBar.setPreferredSize(new java.awt.Dimension(126, 45));
        pnl_tiltleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_tiltleBarMouseDragged(evt);
            }
        });
        pnl_tiltleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_tiltleBarMousePressed(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(255, 0, 0));
        btn_sair.setForeground(new java.awt.Color(255, 255, 255));
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        btn_sair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sair.setFocusPainted(false);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_minimizar.setBackground(new java.awt.Color(40, 46, 62));
        btn_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/min.png"))); // NOI18N
        btn_minimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizar.setFocusPainted(false);
        btn_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_tiltleBarLayout = new javax.swing.GroupLayout(pnl_tiltleBar);
        pnl_tiltleBar.setLayout(pnl_tiltleBarLayout);
        pnl_tiltleBarLayout.setHorizontalGroup(
            pnl_tiltleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tiltleBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnl_tiltleBarLayout.setVerticalGroup(
            pnl_tiltleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tiltleBarLayout.createSequentialGroup()
                .addGroup(pnl_tiltleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pnl_result.setBackground(new java.awt.Color(22, 26, 35));
        pnl_result.setPreferredSize(new java.awt.Dimension(48, 174));

        tfd_formula.setEditable(false);
        tfd_formula.setBackground(new java.awt.Color(22, 26, 35));
        tfd_formula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfd_formula.setForeground(new java.awt.Color(255, 255, 255));
        tfd_formula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfd_formula.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        tfd_result.setEditable(false);
        tfd_result.setBackground(new java.awt.Color(22, 26, 35));
        tfd_result.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfd_result.setForeground(new java.awt.Color(255, 255, 255));
        tfd_result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfd_result.setText("0");
        tfd_result.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfd_result.setPreferredSize(new java.awt.Dimension(11, 32));

        javax.swing.GroupLayout pnl_resultLayout = new javax.swing.GroupLayout(pnl_result);
        pnl_result.setLayout(pnl_resultLayout);
        pnl_resultLayout.setHorizontalGroup(
            pnl_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_resultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfd_formula)
                    .addComponent(tfd_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_resultLayout.setVerticalGroup(
            pnl_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_resultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfd_formula, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfd_result, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_btns.setBackground(new java.awt.Color(52, 60, 79));
        pnl_btns.setPreferredSize(new java.awt.Dimension(322, 414));

        btn_limpar.setBackground(new java.awt.Color(40, 46, 62));
        btn_limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpar.setText("C");
        btn_limpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpar.setFocusPainted(false);
        btn_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_limparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_limparMouseExited(evt);
            }
        });
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_divisao.setBackground(new java.awt.Color(40, 46, 62));
        btn_divisao.setForeground(new java.awt.Color(255, 255, 255));
        btn_divisao.setText("/");
        btn_divisao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_divisao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_divisao.setFocusPainted(false);
        btn_divisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_divisaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_divisaoMouseExited(evt);
            }
        });
        btn_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisaoActionPerformed(evt);
            }
        });

        btn_multiplicar.setBackground(new java.awt.Color(40, 46, 62));
        btn_multiplicar.setForeground(new java.awt.Color(255, 255, 255));
        btn_multiplicar.setText("*");
        btn_multiplicar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_multiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_multiplicar.setFocusPainted(false);
        btn_multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_multiplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_multiplicarMouseExited(evt);
            }
        });
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });

        btn_fechaParentese.setBackground(new java.awt.Color(40, 46, 62));
        btn_fechaParentese.setForeground(new java.awt.Color(255, 255, 255));
        btn_fechaParentese.setText(")");
        btn_fechaParentese.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_fechaParentese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_fechaParentese.setFocusPainted(false);
        btn_fechaParentese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_fechaParenteseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_fechaParenteseMouseExited(evt);
            }
        });
        btn_fechaParentese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechaParenteseActionPerformed(evt);
            }
        });

        btn_abreParentese.setBackground(new java.awt.Color(40, 46, 62));
        btn_abreParentese.setForeground(new java.awt.Color(255, 255, 255));
        btn_abreParentese.setText("(");
        btn_abreParentese.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_abreParentese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_abreParentese.setFocusPainted(false);
        btn_abreParentese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_abreParenteseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_abreParenteseMouseExited(evt);
            }
        });
        btn_abreParentese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abreParenteseActionPerformed(evt);
            }
        });

        btn_subtrair.setBackground(new java.awt.Color(40, 46, 62));
        btn_subtrair.setForeground(new java.awt.Color(255, 255, 255));
        btn_subtrair.setText("-");
        btn_subtrair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_subtrair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_subtrair.setFocusPainted(false);
        btn_subtrair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_subtrairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_subtrairMouseExited(evt);
            }
        });
        btn_subtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subtrairActionPerformed(evt);
            }
        });

        btn_soma.setBackground(new java.awt.Color(40, 46, 62));
        btn_soma.setForeground(new java.awt.Color(255, 255, 255));
        btn_soma.setText("+");
        btn_soma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_soma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_soma.setFocusPainted(false);
        btn_soma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_somaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_somaMouseExited(evt);
            }
        });
        btn_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_somaActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(51, 59, 80));
        btn_7.setForeground(new java.awt.Color(255, 255, 255));
        btn_7.setText("7");
        btn_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_7.setFocusPainted(false);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(51, 59, 80));
        btn_8.setForeground(new java.awt.Color(255, 255, 255));
        btn_8.setText("8");
        btn_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_8.setFocusPainted(false);
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(51, 59, 80));
        btn_9.setForeground(new java.awt.Color(255, 255, 255));
        btn_9.setText("9");
        btn_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_9.setFocusPainted(false);
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(51, 59, 80));
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setText("4");
        btn_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_4.setFocusPainted(false);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(51, 59, 80));
        btn_5.setForeground(new java.awt.Color(255, 255, 255));
        btn_5.setText("5");
        btn_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_5.setFocusPainted(false);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(51, 59, 80));
        btn_6.setForeground(new java.awt.Color(255, 255, 255));
        btn_6.setText("6");
        btn_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_6.setFocusPainted(false);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_resultado.setBackground(new java.awt.Color(83, 179, 105));
        btn_resultado.setForeground(new java.awt.Color(255, 255, 255));
        btn_resultado.setText("=");
        btn_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_resultado.setFocusPainted(false);
        btn_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultadoActionPerformed(evt);
            }
        });

        btn_ponto.setBackground(new java.awt.Color(51, 59, 80));
        btn_ponto.setForeground(new java.awt.Color(255, 255, 255));
        btn_ponto.setText(".");
        btn_ponto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_ponto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ponto.setFocusPainted(false);
        btn_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pontoActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(51, 59, 80));
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setText("3");
        btn_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_3.setFocusPainted(false);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(51, 59, 80));
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.setText("1");
        btn_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_1.setFocusPainted(false);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(51, 59, 80));
        btn_0.setForeground(new java.awt.Color(255, 255, 255));
        btn_0.setText("0");
        btn_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_0.setFocusPainted(false);
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(51, 59, 80));
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setText("2");
        btn_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_2.setFocusPainted(false);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_00.setBackground(new java.awt.Color(51, 59, 80));
        btn_00.setForeground(new java.awt.Color(255, 255, 255));
        btn_00.setText("00");
        btn_00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_00.setFocusPainted(false);
        btn_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_00ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_btnsLayout = new javax.swing.GroupLayout(pnl_btns);
        pnl_btns.setLayout(pnl_btnsLayout);
        pnl_btnsLayout.setHorizontalGroup(
            pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnsLayout.createSequentialGroup()
                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_subtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnsLayout.createSequentialGroup()
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_btnsLayout.createSequentialGroup()
                        .addComponent(btn_abreParentese, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fechaParentese, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_limpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btnsLayout.createSequentialGroup()
                        .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_btnsLayout.createSequentialGroup()
                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_btnsLayout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_btnsLayout.setVerticalGroup(
            pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fechaParentese, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abreParentese, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_subtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_btnsLayout.createSequentialGroup()
                        .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_mainLayout = new javax.swing.GroupLayout(pnl_main);
        pnl_main.setLayout(pnl_mainLayout);
        pnl_mainLayout.setHorizontalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_tiltleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(pnl_result, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(pnl_btns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_mainLayout.setVerticalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addComponent(pnl_tiltleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_btns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizarActionPerformed

    private void pnl_tiltleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_tiltleBarMousePressed
        // TODO add your handling code here:
        LayoutX = evt.getX();
        LayoutY = evt.getY();
    }//GEN-LAST:event_pnl_tiltleBarMousePressed

    private void pnl_tiltleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_tiltleBarMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - LayoutX, evt.getYOnScreen() - LayoutY);
    }//GEN-LAST:event_pnl_tiltleBarMouseDragged

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        formula += "0";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_00ActionPerformed
        // TODO add your handling code here:
        formula += "00";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_00ActionPerformed

    private void btn_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pontoActionPerformed
        // TODO add your handling code here:
        formula += ".";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_pontoActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        formula += "1";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        formula += "2";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        formula += "3";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        formula += "4";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        formula += "5";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        formula += "6";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        formula += "7";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        formula += "8";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        formula += "9";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        formula = "";
        tfd_formula.setText(formula);
        tfd_result.setText("0");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_abreParenteseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abreParenteseActionPerformed
        // TODO add your handling code here:
        formula += "(";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_abreParenteseActionPerformed

    private void btn_fechaParenteseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechaParenteseActionPerformed
        // TODO add your handling code here:
        formula += ")";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_fechaParenteseActionPerformed

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        // TODO add your handling code here:
        formula += " * ";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void btn_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisaoActionPerformed
        // TODO add your handling code here:
        formula += " / ";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_divisaoActionPerformed

    private void btn_subtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subtrairActionPerformed
        // TODO add your handling code here:
        formula += " - ";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_subtrairActionPerformed

    private void btn_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_somaActionPerformed
        // TODO add your handling code here:
        formula += " + ";
        tfd_formula.setText(formula);
    }//GEN-LAST:event_btn_somaActionPerformed

    private void btn_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultadoActionPerformed
        // TODO add your handling code here:
        try {
            if (tfd_formula.getText().equals("")) {
                tfd_result.setText("0");
            }else{
                tfd_formula.setText("");
                tfd_result.setText( gshell.evaluate(formula).toString() );
            }
        } catch (Exception e) {
            tfd_result.setText("ERRO");
        }
    }//GEN-LAST:event_btn_resultadoActionPerformed

    private void btn_limparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparMouseEntered
        // TODO add your handling code here:
        btn_limpar.setBackground(new Color(78,43,181));
    }//GEN-LAST:event_btn_limparMouseEntered

    private void btn_limparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparMouseExited
        // TODO add your handling code here:
        btn_limpar.setBackground(new Color(40,46,62));
    }//GEN-LAST:event_btn_limparMouseExited

    private void btn_abreParenteseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_abreParenteseMouseEntered
        // TODO add your handling code here:
        btn_abreParentese.setBackground(new Color(78,43,181));
    }//GEN-LAST:event_btn_abreParenteseMouseEntered

    private void btn_abreParenteseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_abreParenteseMouseExited
        // TODO add your handling code here:
         btn_abreParentese.setBackground(new Color(40,46,62));
    }//GEN-LAST:event_btn_abreParenteseMouseExited

    private void btn_fechaParenteseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fechaParenteseMouseEntered
        // TODO add your handling code here:
        btn_fechaParentese.setBackground(new Color(78,43,181));
    }//GEN-LAST:event_btn_fechaParenteseMouseEntered

    private void btn_fechaParenteseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fechaParenteseMouseExited
        // TODO add your handling code here:
        btn_fechaParentese.setBackground(new Color(40,46,62));
    }//GEN-LAST:event_btn_fechaParenteseMouseExited

    private void btn_multiplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multiplicarMouseEntered
        // TODO add your handling code here:
        btn_multiplicar.setBackground(new Color(78,43,181));
    }//GEN-LAST:event_btn_multiplicarMouseEntered

    private void btn_multiplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multiplicarMouseExited
        // TODO add your handling code here:
        btn_multiplicar.setBackground(new Color(40,46,62));
    }//GEN-LAST:event_btn_multiplicarMouseExited

    private void btn_divisaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_divisaoMouseEntered
        // TODO add your handling code here:
        btn_divisao.setBackground(new Color(78,43,181));
    }//GEN-LAST:event_btn_divisaoMouseEntered

    private void btn_divisaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_divisaoMouseExited
        // TODO add your handling code here:
        btn_divisao.setBackground(new Color(40,46,62));
    }//GEN-LAST:event_btn_divisaoMouseExited

    private void btn_subtrairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subtrairMouseEntered
        // TODO add your handling code here:
        btn_subtrair.setBackground(new Color(78,43,181));
    }//GEN-LAST:event_btn_subtrairMouseEntered

    private void btn_subtrairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subtrairMouseExited
        // TODO add your handling code here:
        btn_subtrair.setBackground(new Color(40,46,62));
    }//GEN-LAST:event_btn_subtrairMouseExited

    private void btn_somaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_somaMouseEntered
        // TODO add your handling code here:
        btn_soma.setBackground(new Color(78,43,181));
    }//GEN-LAST:event_btn_somaMouseEntered

    private void btn_somaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_somaMouseExited
        // TODO add your handling code here:
        btn_soma.setBackground(new Color(40,46,62));
    }//GEN-LAST:event_btn_somaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_00;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_abreParentese;
    private javax.swing.JButton btn_divisao;
    private javax.swing.JButton btn_fechaParentese;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_minimizar;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_ponto;
    private javax.swing.JButton btn_resultado;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_soma;
    private javax.swing.JButton btn_subtrair;
    private javax.swing.JPanel pnl_btns;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPanel pnl_result;
    private javax.swing.JPanel pnl_tiltleBar;
    private javax.swing.JTextField tfd_formula;
    private javax.swing.JTextField tfd_result;
    // End of variables declaration//GEN-END:variables
}
